# -*- coding: utf-8 -*-
"""Emizan_Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b30pBST8JJiT9dLoXspqmDYKGXDatg70
"""

import numpy as np
import matplotlib.pyplot as plt
import os

os.makedirs("figures", exist_ok=True)

def quat_normalize(q):
    return q / np.linalg.norm(q)

def quat_multiply(q1, q2):
    w1, x1, y1, z1 = q1
    w2, x2, y2, z2 = q2

    return np.array([
        w1*w2 - x1*x2 - y1*y2 - z1*z2,
        w1*x2 + x1*w2 + y1*z2 - z1*y2,
        w1*y2 - x1*z2 + y1*w2 + z1*x2,
        w1*z2 + x1*y2 - y1*x2 + z1*w2
    ])

def quat_to_dcm(q):
    q = quat_normalize(q)
    w, x, y, z = q

    return np.array([
        [1-2*(y**2+z**2), 2*(x*y - z*w), 2*(x*z + y*w)],
        [2*(x*y + z*w), 1-2*(x**2+z**2), 2*(y*z - x*w)],
        [2*(x*z - y*w), 2*(y*z + x*w), 1-2*(x**2+y**2)]
    ])

def small_angle_quat(dtheta):
    dq = np.zeros(4)
    dq[0] = 1.0
    dq[1:] = 0.5 * dtheta
    return quat_normalize(dq)

"""Quaternion + Rotation"""

def omega_dot(omega, J):
    return np.linalg.inv(J) @ (-np.cross(omega, J @ omega))

def quat_dot(q, omega):
    wx, wy, wz = omega
    Omega = np.array([
        [0, -wx, -wy, -wz],
        [wx, 0, wz, -wy],
        [wy, -wz, 0, wx],
        [wz, wy, -wx, 0]
    ])
    return 0.5 * Omega @ q

def rk4_step(q, omega, dt, J):
    k1_q = quat_dot(q, omega)
    k1_w = omega_dot(omega, J)

    k2_q = quat_dot(q + 0.5*dt*k1_q, omega + 0.5*dt*k1_w)
    k2_w = omega_dot(omega + 0.5*dt*k1_w, J)

    k3_q = quat_dot(q + 0.5*dt*k2_q, omega + 0.5*dt*k2_w)
    k3_w = omega_dot(omega + 0.5*dt*k2_w, J)

    k4_q = quat_dot(q + dt*k3_q, omega + dt*k3_w)
    k4_w = omega_dot(omega + dt*k3_w, J)

    q_next = q + (dt/6)*(k1_q + 2*k2_q + 2*k3_q + k4_q)
    omega_next = omega + (dt/6)*(k1_w + 2*k2_w + 2*k3_w + k4_w)

    return quat_normalize(q_next), omega_next

"""Dynamics"""

def omega_dot(omega, J):
    return np.linalg.inv(J) @ (-np.cross(omega, J @ omega))

def quat_dot(q, omega):
    wx, wy, wz = omega
    Omega = np.array([
        [0, -wx, -wy, -wz],
        [wx, 0, wz, -wy],
        [wy, -wz, 0, wx],
        [wz, wy, -wx, 0]
    ])
    return 0.5 * Omega @ q

def rk4_step(q, omega, dt, J):
    k1_q = quat_dot(q, omega)
    k1_w = omega_dot(omega, J)

    k2_q = quat_dot(q + 0.5*dt*k1_q, omega + 0.5*dt*k1_w)
    k2_w = omega_dot(omega + 0.5*dt*k1_w, J)

    k3_q = quat_dot(q + 0.5*dt*k2_q, omega + 0.5*dt*k2_w)
    k3_w = omega_dot(omega + 0.5*dt*k2_w, J)

    k4_q = quat_dot(q + dt*k3_q, omega + dt*k3_w)
    k4_w = omega_dot(omega + dt*k3_w, J)

    q_next = q + (dt/6)*(k1_q + 2*k2_q + 2*k3_q + k4_q)
    omega_next = omega + (dt/6)*(k1_w + 2*k2_w + 2*k3_w + k4_w)

    return quat_normalize(q_next), omega_next

"""SENSOR MODELS (vector, star tracker & gyroscope)"""

import numpy as np

def quat_to_dcm(q):
    """
    Convert quaternion to Direction Cosine Matrix (DCM).
    q = [q0, q1, q2, q3] where q0 is scalar part
    """
    q0, q1, q2, q3 = q

    R = np.array([
        [1 - 2*(q2**2 + q3**2),     2*(q1*q2 - q0*q3),     2*(q1*q3 + q0*q2)],
        [    2*(q1*q2 + q0*q3), 1 - 2*(q1**2 + q3**2),     2*(q2*q3 - q0*q1)],
        [    2*(q1*q3 - q0*q2),     2*(q2*q3 + q0*q1), 1 - 2*(q1**2 + q2**2)]
    ])

    return R


def vector_sensor(v_inertial, q):
    """
    Magnetometer measurement model for HMR2300.

    Measurement equation: y = M @ R^T @ v_inertial + b + w

    where:
        M  : 3x3 scale factor / misalignment matrix
        R  : Direction Cosine Matrix from quaternion
        b  : 3x1 bias/offset vector
        w  : 3x1 Gaussian noise

    Parameters:
    -----------
    v_inertial : np.ndarray, shape (3,)
        Magnetic field vector in inertial frame [gauss]
    q : np.ndarray, shape (4,)
        Unit quaternion [q0, q1, q2, q3]

    Returns:
    --------
    y : np.ndarray, shape (3,)
        Measured magnetic field in body frame [gauss]
    y_true : np.ndarray, shape (3,)
        True (noise-free, unbiased) measurement
    """


    R = quat_to_dcm(q)
    v_body_true = R.T @ v_inertial


    scale_error = 0.005  # ±0.5% gain error
    misalignment = 0.002  # ~0.1 degrees in rad, converted to fraction

    M = np.array([
        [1 + scale_error,           misalignment,          -misalignment],
        [-misalignment,     1 + scale_error,               misalignment],
        [misalignment,             -misalignment,    1 + scale_error]
    ])

    # b = [X_bias, Y_bias, Z_bias] in Gauss
    #ASTERIA has a residual dipole moment, measured at 0.17 Am2 preflight (Pong 2018) in the Z-axis
    # We use the 0.6 mG datasheet offset + ASTERIA's known Z-bias
    b = np.array([0.0006, -0.0006, 0.1706])

    # Noise covariance matrix W
    # The datasheet says accuracy is < 0.5% of Full Scale (2 Gauss)
    # 0.005 * 2 = 0.01
    noise_std = .01
    W = (noise_std**2) * np.eye(3)

    # Generate Gaussian noise
    w = np.random.multivariate_normal(np.zeros(3), W)

    # Apply measurement model
    # y = M @ R^T @ v_inertial + b + w
    y_true = M @ v_body_true
    y = y_true + b + w

    return y, y_true, {
        'M': M,
        'b': b,
        'w': w,
        'W': W,
        'R': R,
        'v_body_true': v_body_true
    }

def star_tracker(q_true):
    sigma_xy = np.deg2rad(0.003)
    sigma_z  = np.deg2rad(0.007)

    cov = np.diag([sigma_xy**2, sigma_xy**2, sigma_z**2])
    delta_theta = np.random.multivariate_normal(np.zeros(3), cov)

    dq = small_angle_quat(delta_theta)
    return quat_multiply(dq, q_true)

import numpy as np

class STIM210Gyro:
    def __init__(self):
        # STIM210 Datasheet Limits
        scale_accuracy = 500e-6  # 500 ppm
        misalignment = 0.001     # 1 mrad

        # Covariance Vector of variances
        # We assume X, Y, and Z axes share the same manufacturing tolerances
        variances = np.array([scale_accuracy**2] * 3 + [misalignment**2] * 6)

        # Sampling errors from a normal distribution
        errors = np.random.normal(0, np.sqrt(variances))

        # Creating covariant Matrix
        # Diagonal = Scale (1 + error)
        # Off-Diagonal = Misalignment (0 + error)
        self.M = np.eye(3)
        self.M[0,0] += errors[0] # Scale X
        self.M[1,1] += errors[1] # Scale Y
        self.M[2,2] += errors[2] # Scale Z

        self.M[0,1], self.M[0,2] = errors[3], errors[4] # Misalignments
        self.M[1,0], self.M[1,2] = errors[5], errors[6]
        self.M[2,0], self.M[2,1] = errors[7], errors[8]

        # Printing matrix
        print(" STIM210 Scale/Misalignment Matrix ---")
        print(self.M)

        # Noise Specs from STIM210 Datasheet
        self.bias_instability = 0.3 / 3600 # 0.3 deg/h
        self.arw = 0.15 / 60              # 0.15 deg/sqrt(h)
        self.b = np.zeros(3)

    def measure(self, omega_true, dt):
        # Low-frequency "walking" bias
        self.b += self.bias_instability * np.sqrt(dt) * np.random.randn(3)

        # High-frequency "vibrating" white noise
        white_noise = (self.arw / np.sqrt(dt)) * np.random.randn(3)

        # Total sensor output: Fingerprint @ Physics + Drift + Noise
        return self.M @ omega_true + self.b + white_noise

# Test it
gyro = STIM210Gyro()

"""Simulation"""

import numpy as np

# Simulation parameters
dt = 1
T = 200
N = int(T/dt)

# ASTERIA Measured Moments of Inertia from Table 2
J = np.diag([0.0969, 0.1235, 0.1918])

# Initial states
q = np.array([1, 0, 0, 0])
omega = np.array([0.1, 0.2, 0.15])
v_inertial_mag = np.array([0.2, 0.0, 0.4]) # Example Earth magnetic field [gauss]

# Initialize sensor objects
gyro = STIM210Gyro()
# If you turned the magnetometer into a class like the others:
# mag_sensor = HMR2300Magnetometer()

omega_hist = []
gyro_hist = []
vec_true = []
vec_meas = []
biases = []

for i in range(N):
    omega_hist.append(omega)

    # 1. Gyro Measurement (STIM210)
    gyro_m = gyro.measure(omega, dt)
    gyro_hist.append(gyro_m)

    # 2. Magnetometer Measurement (HMR2300)
    # Using the function you provided:
    y_meas, y_true, params = vector_sensor(v_inertial_mag, q)

    vec_true.append(y_true)
    vec_meas.append(y_meas)
    biases.append(params['b'])   # <-- store bias

    # 3. Propagation
    # Advance the physics using your RK4 integrator
    q, omega = rk4_step(q, omega, dt, J)

"""Run

PLOTS
"""

plt.figure()
plt.plot(omega_hist, label="true")
plt.plot(gyro_hist, linestyle='--', alpha=0.7)
plt.title("Gyroscope Measurement vs Truth (Sampling = 1 Hz)")
plt.savefig("figures/gyro.png", dpi=300)
plt.show()

vec_true = np.array(vec_true)
vec_meas = np.array(vec_meas)

plt.figure()
plt.plot(vec_true[:,0], label="true")
plt.plot(vec_meas[:,0], linestyle='--', label="measured")
plt.legend()
plt.title("Vector Sensor Measurement")
plt.savefig("figures/vector.png", dpi=300)
plt.show()

residuals = np.array(vec_meas) - np.array(vec_true)

plt.plot(residuals[:,0], label='X-axis error')
plt.plot(residuals[:,1], label='Y-axis error')
plt.plot(residuals[:,2], label='Z-axis error')

plt.title("Magnetometer Residuals (Error Only)")
plt.ylabel("Gauss")
plt.xlabel("Time Step")
plt.legend()
plt.grid(True)

residuals = np.array(vec_meas) - np.array(vec_true)
b = biases[0]   # bias is constant, so just take the first one

# Subtract bias if you want noise-only
residuals_no_bias = residuals - b

plt.plot(residuals_no_bias[:,0], label='X-axis error')
plt.plot(residuals_no_bias[:,1], label='Y-axis error')
plt.plot(residuals_no_bias[:,2], label='Z-axis error')

plt.title("Magnetometer Residuals (Noise Only)")
plt.ylabel("Gauss")
plt.xlabel("Time Step")
plt.legend()
plt.grid(True)

plt.figure()
plt.plot(star_err)
plt.title("Star Tracker Error Magnitude")
plt.savefig("figures/star.png", dpi=300)
plt.show()