# -*- coding: utf-8 -*-
"""Emizan4_Parts1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sc7JwvF2Dw1VqzhFkV8EyJI8-RcAERJh
"""

import numpy as np
import matplotlib.pyplot as plt

# =========================
# CONSTANTS
# =========================

mu = 3.986e14                 # Earth gravitational parameter [m^3/s^2]
R_earth = 6371e3              # Earth radius [m]
h = 400e3                     # Orbit altitude [m]

r_orbit = R_earth + h
omega_orbit = np.sqrt(mu / r_orbit**3)

T_orbit = 2*np.pi / omega_orbit

print("Orbital period [min]:", T_orbit/60)

# =========================
# INERTIA MATRIX
# =========================

I = np.diag([0.0867, 0.1817, 0.1117])
I_inv = np.linalg.inv(I)

def gravity_gradient_torque(t):

    # Earth direction in body frame
    r_hat = np.array([
        np.cos(omega_orbit*t),
        np.sin(omega_orbit*t),
        0
    ])

    torque = 3 * omega_orbit**2 * np.cross(r_hat, I @ r_hat)

    return torque

rho = 1e-12             # kg/m^3
Cd = 2.2
A = 0.04                # m^2 projected area

v_mag = np.sqrt(mu/r_orbit)

# center of pressure offset from center of mass
r_cp = np.array([0.02, 0.01, 0.0])   # meters

def drag_torque(t):

    # velocity direction rotating in body frame
    v_hat = np.array([
        -np.sin(omega_orbit*t),
         np.cos(omega_orbit*t),
         0
    ])

    v_vec = v_mag * v_hat

    F_drag = -0.5 * rho * Cd * A * np.linalg.norm(v_vec) * v_vec

    torque = np.cross(r_cp, F_drag)

    return torque

def total_torque(t):

    tau_gg = gravity_gradient_torque(t)
    tau_drag = drag_torque(t)

    return tau_gg + tau_drag

def omega_dot(omega, torque):

    gyro_term = np.cross(omega, I @ omega)

    return I_inv @ (torque - gyro_term)

# =========================
# SIMULATION
# =========================

dt = 1.0                           # seconds
num_orbits = 5

t_final = num_orbits * T_orbit

times = np.arange(0, t_final, dt)

# Initial angular velocity
omega = np.radians([0.1, 0.05, -0.08])

omegas = []
tau_gg_hist = []
tau_drag_hist = []
tau_total_hist = []
H_hist = []

for t in times:

    tau_gg = gravity_gradient_torque(t)
    tau_drag = drag_torque(t)

    tau_total = tau_gg + tau_drag

    # dynamics
    domega = omega_dot(omega, tau_total)

    omega = omega + domega * dt

    # angular momentum
    H = I @ omega

    omegas.append(omega.copy())
    tau_gg_hist.append(np.linalg.norm(tau_gg))
    tau_drag_hist.append(np.linalg.norm(tau_drag))
    tau_total_hist.append(np.linalg.norm(tau_total))
    H_hist.append(np.linalg.norm(H))

omegas = np.array(omegas)
tau_gg_hist = np.array(tau_gg_hist)
tau_drag_hist = np.array(tau_drag_hist)
tau_total_hist = np.array(tau_total_hist)
H_hist = np.array(H_hist)

print("Max Gravity Gradient Torque:", np.max(tau_gg_hist))
print("Max Drag Torque:", np.max(tau_drag_hist))

print("Average GG Torque:", np.mean(tau_gg_hist))
print("Average Drag Torque:", np.mean(tau_drag_hist))

daily_seconds = 86400

H_gg_day = np.mean(tau_gg_hist) * daily_seconds
H_drag_day = np.mean(tau_drag_hist) * daily_seconds

print("Daily Momentum Build-up:")
print("GG:", H_gg_day)
print("Drag:", H_drag_day)

plt.figure(figsize=(10,5))

plt.plot(times/3600, tau_gg_hist, label='Gravity Gradient')
plt.plot(times/3600, tau_drag_hist, label='Atmospheric Drag')

plt.xlabel('Time [hours]')
plt.ylabel('Torque Magnitude [Nm]')
plt.title('Environmental Disturbance Torques')
plt.legend()
plt.grid()

plt.show()

plt.figure(figsize=(10,5))

plt.plot(times/3600, H_hist)

plt.xlabel('Time [hours]')
plt.ylabel('Angular Momentum [Nms]')
plt.title('Angular Momentum Evolution')

plt.grid()

plt.show()